[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vesti_escrow = "H1cs7KqkmmPXMEppuTa7VrVC1apSaYtqUD5hJekwQqyC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo \"Add Anchor tests in a later on-chain iteration\""

[hooks]
