[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vesti_escrow = "ErFsmiKY7WxjD9ArYmpqjCCUKnTcfzLm6tFpmWdFU9ck"

[programs.devnet]
vesti_escrow = "ErFsmiKY7WxjD9ArYmpqjCCUKnTcfzLm6tFpmWdFU9ck"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo \"Add Anchor tests in a later on-chain iteration\""

[hooks]
